name: Semgrep Scan

on:
  pull_request:
  push:
    branches: [main]

jobs:
  semgrep:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Semgrep scan
      uses: returntocorp/semgrep-action@v1
      with:
        config: 'auto'
