name: Manual ZAP Full Scan

on:
  workflow_dispatch:  # Only runs when manually triggered

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan the Web Application

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: master

      - name: Run ZAP Full Scan
        id: zap
        uses: zaproxy/action-full-scan@v0.12.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          target: 'https://www.zaproxy.org/'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'

      - name: Display ZAP Alerts Summary
        run: |
          if [ -f report_json.json ]; then
            echo "### ⚠️ ZAP Alerts Summary" >> $GITHUB_STEP_SUMMARY
            jq -r '.site[].alerts[] | "- **\(.risk)**: \(.alert) (\(.confidence))"' report_json.json >> $GITHUB_STEP_SUMMARY
          else
            echo "No ZAP JSON report found." >> $GITHUB_STEP_SUMMARY
        shell: bash

      - name: Upload ZAP Reports
        uses: actions/upload-artifact@v4
        with:
          name: zap-full-scan-reports
          path: |
            report_html.html
            report_json.json
