name: Dev SAST Pipeline

on:
    push:
      branches: [ "main" ]
  
    # Leave this empty (i.e., pull_request:) to trigger on PRs to all branches
    # pull_request:
    #   branches: [ "main" ]  

    pull_request_target:
      branches: [ "main" ]  # Only triggers on PRs targeting 'main'
  
    # Scheduled run every Friday at 12:00 PM IST (6:30 AM UTC)
    # schedule:
    #   - cron: '30 6 * * 5'
  
jobs:
  sast:
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
      pull-requests: write # for commenting on PRs with LLM suggestions

    name: Run SAST (Bandit + Semgrep + Gitleaks)
    runs-on: ubuntu-latest

    steps:
      # - name: Checkout code
      #   uses: actions/checkout@v3
      - name: Checkout PR branch (for pull_request_target)
        if: github.event_name == 'pull_request_target'
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          fetch-depth: 0
          # Fetch both base and head for diff
          # This ensures both refs are available for git diff

      - name: Checkout main code (for push or pull_request)
        if: github.event_name != 'pull_request_target'
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Pull full history

      - name: Get changed files
        id: changed-files
        run: |
          if [[ "${{ github.event_name }}" == "pull_request_target" ]]; then
            echo "🔍 Detected PR scan (pull_request_target)..."

            BASE_REF="${{ github.event.pull_request.base.ref }}"   # usually 'main'
            BASE_REPO="${{ github.event.pull_request.base.repo.full_name }}"
            HEAD_REF="${{ github.event.pull_request.head.ref }}"
            HEAD_REPO="${{ github.event.pull_request.head.repo.full_name }}"
            HEAD_SHA="${{ github.event.pull_request.head.sha }}"   # latest PR commit

            echo "Fetching base branch: $BASE_REF from $BASE_REPO"
            git fetch https://github.com/$BASE_REPO.git $BASE_REF:$BASE_REF
            echo "Fetching head branch: $HEAD_REF from $HEAD_REPO"
            git fetch https://github.com/$HEAD_REPO.git $HEAD_REF:$HEAD_REF

            echo "📏 Comparing base ($BASE_REF) with PR head commit ($HEAD_REF)..."
            files=$(git diff --name-only $BASE_REF...$HEAD_REF)
          else
            echo "📦 Detected push event..."
            files=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})
          fi

          echo "📁 Changed files:"
          echo "$files"

          echo "files<<EOF" >> $GITHUB_OUTPUT
          echo "$files" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT


      - name: Stop if no files changed
        if: steps.changed-files.outputs.files == ''
        run: |
          echo "🛑 No files changed. Skipping rest of the pipeline."
          exit 0


      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Bandit and converter
        run: |
          pip install bandit
          # pip install bandit-sarif-formatter
      
      - name: Install Semgrep CLI
        run: pip install semgrep

      # - name: Run Bandit (on changed files)
      #   if: steps.changes.outputs.files != ''
      #   run: |
      #     mkdir -p reports
      #     bandit -x tests -f json -o reports/bandit_report.json -ll -iii ${{ steps.changes.outputs.files }} || true

      - name: Run Bandit
        run: |
          # Create a 'reports' directory if it doesn't exist
          mkdir -p reports
      
          # Run Bandit on the entire project directory (recursive)
          # -x tests        → exclude the 'tests' folder
          # -f json         → output the results in JSON format
          # -o ...          → save the output to 'reports/bandit_report.json'
          # -ll             → include low, medium, and high severity issues
          # -iii            → show issue context lines in the report
          bandit -r . \
            -x tests \
            -f json \
            -o reports/bandit_report.json \
            -ll -iii || true
          
      #     bandit -r . \
      #       -x tests \
      #       --format sarif \
      #       --output reports/bandit_report.sarif || true

      # - name: Upload Bandit SARIF to GitHub Security tab
      #   uses: github/codeql-action/upload-sarif@v3
      #   with:
      #     sarif_file: reports/bandit_report.sarif
      #     category: bandit
      
      # - name: Run Semgrep (on changed files)
      #   if: steps.changes.outputs.files != ''
      #   run: |
      #     mkdir -p reports
      #     semgrep --config auto \
      #             --exclude tests \
      #             --json \
      #             --output reports/semgrep_report.json \
      #             ${{ steps.changes.outputs.files }} || true
      #   env:
      #     SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}


      # - name: Login to Semgrep
      #   run: semgrep login
      #   env:
      #     SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
      
      - name: Run Semgrep via CLI
        run: |
          mkdir -p reports

          semgrep --config auto \
                  --exclude tests \
                  --json \
                  --output reports/semgrep_report.json || true
          
      #     semgrep --config auto \
      #             --exclude tests \
      #             --sarif \
      #             --output reports/semgrep_report.sarif || true   
        env:
            SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}           

      # - name: Upload Semgrep SARIF to GitHub Security tab
      #   uses: github/codeql-action/upload-sarif@v3
      #   with:
      #     sarif_file: reports/semgrep_report.sarif
      #     category: semgrep
      
      - name: Install Gitleaks
        run: |
          curl -sSL https://github.com/gitleaks/gitleaks/releases/download/v8.27.2/gitleaks_8.27.2_linux_x64.tar.gz -o gitleaks.tar.gz
          tar -xzf gitleaks.tar.gz
          sudo mv gitleaks /usr/local/bin/
          gitleaks version

      - name: Run Gitleaks (JSON + SARIF)
        run: |
          mkdir -p reports

          # JSON report
          gitleaks detect \
            --source . \
            --no-git \
            --report-format json \
            --report-path reports/gitleaks_report.json || true

          # # SARIF report (for GitHub Security)
          # gitleaks detect \
          #   --source . \
          #   --no-git \
          #   --report-format sarif \
          #   --report-path reports/gitleaks_report.sarif || true

      # - name: Upload Gitleaks SARIF to GitHub Security tab
      #   uses: github/codeql-action/upload-sarif@v3
      #   with:
      #     sarif_file: reports/gitleaks_report.sarif
      #     category: gitleaks


      # Makes the report downloadable from the Actions tab
      - name: Upload Bandit, Semgrep and Gitleaks reports
        uses: actions/upload-artifact@v4
        with:
          name: security-reports
          path: reports/
              
      
      - name: Combine SAST JSON reports
        run: python combine_reports.py

      - name: Deduplicate issues
        run: python deduplicate_reports.py

      - name: Install dotenv and google-generativeai 
        run: pip install google-generativeai dotenv

      - name: Generate LLM resolutions
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: python get_resolutions.py

      - name: Convert to SARIF
        run: python resolution2sarif.py

      - name: Upload final_report SARIF to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: reports/final_report.sarif
          category: ai-sast-dast-pipeline
      
      # - name: Comment on PR with LLM suggestions
      #   if: github.event_name == 'pull_request_target'
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     GITHUB_REPOSITORY: ${{ github.repository }}
      #     PR_NUMBER: ${{ github.event.pull_request.number }}
      #   run: |
      #     pip install requests
      #     python comment_on_pr.py